# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Build and Test AutoSD

on:
  pull_request:
  workflow_dispatch:

jobs:
  lola-demo:
    name: lola-demo
    runs-on: ubuntu-latest
    env:
      USE_BAZEL_VERSION: 8.3.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-version: 1.x

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman curl qemu-system which createrepo-c pip make git
          # remove the follwing line once qemu driver changes are released
          pip install uv

      - name: Build and copy RPMs
        run: ./build-rpms.sh
        working-directory: reference_integration

      - name: Build AutoSD Image
        uses: ./.github/actions/aib
        with:
          manifest: image.aib.yml
          distro: autosd10
          mode: package
          target: qemu
          export: qcow2
          extra_args: '--define-file vars-devel.yml --define-file vars.yml'
          disk_path: disk.qcow2
          base_dir: os_images

      - name: Enable KVM group perms
        run: |
          sudo usermod -aG kvm $USER
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo modprobe vhost_vsock

      - name: Install Jumpstarter
        run: |
          # use it once qemu changes are published
          # pip install --extra-index-url https://pkg.jumpstarter.dev/ jumpstarter-all
          git clone -b main https://github.com/jumpstarter-dev/jumpstarter.git /tmp/jumpstarter
          make -C /tmp/jumpstarter/python build
          pip install /tmp/jumpstarter/python/dist/*.whl

      - name: Test QEMU Image
        run: |
          SSH_PASSWORD=password jmp shell --exporter-config jumpstarter/qemu.exporter.yaml < jumpstarter/qemu.cmd.sh

          exit $(cat /tmp/jmp.rc.txt)
